Change nightly test triggers
Now the tests are triggered when:
- run-k8s-dist-tests label is added into PR
- or when the PR is merged into master branch and run-k8s-dist-tests
  label is not present in the PR

diff --git a/.github/workflows/e2e-eks.yaml b/.github/workflows/e2e-eks.yaml
--- a/.github/workflows/e2e-eks.yaml
+++ b/.github/workflows/e2e-eks.yaml
@@ -1,12 +1,26 @@
-name: Nightly E2E tests on AWS
+name: E2E tests on AWS
 on:
   workflow_dispatch:
-  schedule:
-    - cron: "0 9 * * *"
+  workflow_call:
+    secrets:
+      NEW_RELIC_LICENCE_KEY:
+        required: true
+      HZ_LICENSE_KEY:
+        required: true
+      AWS_ACCESS_KEY_ID:
+        required: true
+      AWS_SECRET_ACCESS_KEY:
+        required: true
+      AZURE_STORAGE_KEY:
+        required: true
+      GKE_SA_KEY:
+        required: true
+      SLACK_WEBHOOK_URL:
+        required: true
 
 env:
   AWS_REGION: us-east-1
-  NEW_RELIC_API_KEY: ${{ secrets.NEW_RELIC_API_KEY }}
+
 jobs:
   prepare-env:
     name: Create EKS cluster
@@ -98,15 +112,10 @@ jobs:
       - name: Build and push image to ttl.sh
         id: build-img
         run: |
-          if [[ "${{github.event_name}}" == "workflow_dispatch" ]]; then
-            IMG=ttl.sh/$(uuidgen):2h
-            echo "IMG=${IMG}" >> $GITHUB_OUTPUT
-            make docker-build-ci IMG=$IMG VERSION=${{github.sha}}
-            make docker-push IMG=$IMG
-          else
-            IMG=hazelcast/hazelcast-platform-operator:latest-snapshot
-            echo "IMG=${IMG}" >> $GITHUB_OUTPUT
-          fi
+          IMG=ttl.sh/$(uuidgen):2h
+          echo "IMG=${IMG}" >> $GITHUB_OUTPUT
+          make docker-build-ci IMG=$IMG VERSION=${{github.sha}}
+          make docker-push IMG=$IMG
 
   eks-e2e-tests:
     name: Run e2e test on EKS
@@ -120,7 +129,7 @@ jobs:
       matrix:
         edition: ["os", "ee"]
     env:
-      NAMESPACE: test-operator-nightly-${{ matrix.edition }}
+      NAMESPACE: test-operator-${{ matrix.edition }}
       NAME_PREFIX: hp-${{ matrix.edition }}-${{ github.run_id }}-
       IMG: ${{ needs.get-image.outputs.IMG }}
     steps:
@@ -236,7 +245,7 @@ jobs:
       - name: Delete EKS cluster
         run: |-
           CLUSTER_NAME="operator-e2e-test-${GITHUB_SHA::8}-${{ github.run_number }}"
-          eksctl delete addon --name aws-ebs-csi-driver --cluster "${CLUSTER_NAME}"
+          eksctl delete addon --name aws-ebs-csi-driver --cluster "${CLUSTER_NAME}" || echo "could not delete addon"
           eksctl delete nodegroup --cluster "${CLUSTER_NAME}" --name node-group-1
           eksctl delete cluster "${CLUSTER_NAME}" --wait
 
