add namespace clean up after tests

diff --git a/.github/workflows/nightly-e2e-aws.yaml b/.github/workflows/nightly-e2e-aws.yaml
--- a/.github/workflows/nightly-e2e-aws.yaml
+++ b/.github/workflows/nightly-e2e-aws.yaml
@@ -35,6 +35,9 @@ jobs:
     name: Run e2e test on EKS
     runs-on: ubuntu-20.04
     needs: "prepare-env"
+    defaults:
+      run:
+        shell: bash
     strategy:
       fail-fast: false
       matrix:
@@ -81,13 +84,20 @@ jobs:
       - name: Deploy Operator to EKS
         run: |
           kubectl create namespace ${NAMESPACE}
+          kubectl config set-context --current --namespace=${NAMESPACE}
+
+          DEPLOY_NAME=${NAME_PREFIX}controller-manager
+          echo "DEPLOY_NAME=${DEPLOY_NAME}" >> $GITHUB_ENV
+
           make deploy NAMESPACE=${NAMESPACE} IMG=${IMG} NAME_PREFIX=${NAME_PREFIX}
+          kubectl rollout status deployment $DEPLOY_NAME
 
       - name: Create secret
         if: matrix.edition == 'ee'
         run: kubectl create secret generic hazelcast-license-key --namespace ${NAMESPACE} --from-literal=license-key=${{ secrets.HZ_LICENSE_KEY }}
 
       - name: Run Hazelcast E2E tests on EKS
+        id: e2e-test
         run: |
           case ${{ matrix.edition }} in
             os) GO_TEST_FLAGS=-ee=false;;
@@ -95,6 +105,31 @@ jobs:
             *)  echo Unexpected edition: ${{ matrix.edition }} && exit 1;;
           esac
           make test-e2e GO_TEST_FLAGS=${GO_TEST_FLAGS} NAMESPACE=${NAMESPACE} NAME_PREFIX=${NAME_PREFIX}
+
+      - name: Clean up after Tests
+        if: ${{ always() }}
+        run: |
+          hz=$(kubectl get hazelcast -o name); [[ "$hz" != "" ]] && kubectl delete $hz --wait=false || echo "no hazelcast resources"
+          mc=$(kubectl get managementcenter -o name); [[ "$mc" != "" ]] && kubectl delete $mc --wait=false || echo "no managementcenter resources"
+          if [[ ${{ steps.e2e-test.outcome }} != 'success' ]]; then
+            i=0
+            while ! kubectl rollout status deployment ${DEPLOY_NAME}; do
+              kubectl rollout restart deployment ${DEPLOY_NAME}
+              if [[ $i == 2 ]]; then echo "Failure testing the operator, namespace ${NAMESPACE} requires manual clean up"; exit 1; fi
+              ((i++))
+            done
+          fi
+          sleep 10
+          hz=$(kubectl get hazelcast -o name)
+          mc=$(kubectl get managementcenter -o name)
+          if [[ $hz != "" ]] || [[ $mc != "" ]]; then
+            echo "Failure deleting hazelcast and managementcenter resources, namespace ${NAMESPACE} requires manual clean up"; exit 1
+          fi
+          if [[ ${{ matrix.edition }} == 'ee' ]]; then
+            kubectl delete secret hazelcast-license-key --wait=false
+          fi
+          make undeploy-keep-crd
+          kubectl delete namespace $NAMESPACE --wait=false
 
   clean-up:
     name: Delete EKS cluster
