Uncomment code

diff --git a/.github/workflows/redhat-connect-release.yaml b/.github/workflows/redhat-connect-release.yaml
--- a/.github/workflows/redhat-connect-release.yaml
+++ b/.github/workflows/redhat-connect-release.yaml
@@ -39,89 +39,89 @@ jobs:
           echo "RHEL_IMAGE=${RHEL_IMAGE}" >> $GITHUB_ENV
           echo "::set-output name=RELEASE_VERSION::${RELEASE_VERSION}"
       
-      # - name: Generate Operator and Operator Image
-      #   run: |
-      #     echo "Building the operator image"
-      #     make docker-build IMG=${RHEL_IMAGE} VERSION="${RELEASE_VERSION}"
+      - name: Generate Operator and Operator Image
+        run: |
+          echo "Building the operator image"
+          make docker-build IMG=${RHEL_IMAGE} VERSION="${RELEASE_VERSION}"
 
-      # - name: Push Hazelcast-Platform-Operator image to RHEL scan registry
-      #   run: |
-      #     docker login ${SCAN_REGISTRY} -u unused -p ${RHEL_REPO_PASSWORD}
-      #     make docker-push IMG=${RHEL_IMAGE} 
+      - name: Push Hazelcast-Platform-Operator image to RHEL scan registry
+        run: |
+          docker login ${SCAN_REGISTRY} -u unused -p ${RHEL_REPO_PASSWORD}
+          make docker-push IMG=${RHEL_IMAGE} 
 
-      # - name: Wait for Scan to Complete
-      #   run: |
-      #     PROJECT_ID=$( echo ${RHEL_REPOSITORY} | grep -m 1 -Po "/\K.+(?=/)" )
-      #     source .github/scripts/publish-rhel.sh
+      - name: Wait for Scan to Complete
+        run: |
+          PROJECT_ID=$( echo ${RHEL_REPOSITORY} | grep -m 1 -Po "/\K.+(?=/)" )
+          source .github/scripts/publish-rhel.sh
 
-      #     wait_for_container_scan "$PROJECT_ID" "$RELEASE_VERSION" "$RHEL_API_KEY" "$TIMEOUT_IN_MINS"
+          wait_for_container_scan "$PROJECT_ID" "$RELEASE_VERSION" "$RHEL_API_KEY" "$TIMEOUT_IN_MINS"
 
-      # - name: Deploy Hazelcast-Platform-Operator to OCP
-      #   run: |
-      #     NAMESPACE=oc-e2e-test-${{ github.run_id}}
-      #     echo "NAMESPACE=${NAMESPACE}" >> $GITHUB_ENV
-      #     oc login ${OCP_CLUSTER_URL} -u=${OCP_USERNAME} -p=${OCP_PASSWORD} --insecure-skip-tls-verify
-      #     oc new-project $NAMESPACE
+      - name: Deploy Hazelcast-Platform-Operator to OCP
+        run: |
+          NAMESPACE=oc-e2e-test-${{ github.run_id}}
+          echo "NAMESPACE=${NAMESPACE}" >> $GITHUB_ENV
+          oc login ${OCP_CLUSTER_URL} -u=${OCP_USERNAME} -p=${OCP_PASSWORD} --insecure-skip-tls-verify
+          oc new-project $NAMESPACE
 
-      #     oc create secret docker-registry pull-secret \
-      #     --docker-server=$SCAN_REGISTRY \
-      #     --docker-username=unused \
-      #     --docker-password=$RHEL_REPO_PASSWORD \
-      #     --docker-email=unused
+          oc create secret docker-registry pull-secret \
+          --docker-server=$SCAN_REGISTRY \
+          --docker-username=unused \
+          --docker-password=$RHEL_REPO_PASSWORD \
+          --docker-email=unused
 
-      #     cat <<EOF | oc apply -f -
-      #     apiVersion: v1
-      #     kind: ServiceAccount
-      #     metadata:
-      #       name: hazelcast-platform-controller-manager
-      #       namespace: $NAMESPACE
-      #     EOF
+          cat <<EOF | oc apply -f -
+          apiVersion: v1
+          kind: ServiceAccount
+          metadata:
+            name: hazelcast-platform-controller-manager
+            namespace: $NAMESPACE
+          EOF
 
-      #     oc secrets link hazelcast-platform-controller-manager pull-secret --for=pull
-      #     make deploy  IMG=$RHEL_IMAGE  NAMESPACE=$NAMESPACE
-      #     oc rollout status deployment hazelcast-platform-controller-manager
+          oc secrets link hazelcast-platform-controller-manager pull-secret --for=pull
+          make deploy  IMG=$RHEL_IMAGE  NAMESPACE=$NAMESPACE
+          oc rollout status deployment hazelcast-platform-controller-manager
 
-      # - name: Test the Operator
-      #   id: e2e-test
-      #   run: |
-      #     oc create secret generic hazelcast-license-key --from-literal=license-key=${HZ_LICENSE_KEY}
-      #     make test-e2e NAMESPACE=$NAMESPACE
+      - name: Test the Operator
+        id: e2e-test
+        run: |
+          oc create secret generic hazelcast-license-key --from-literal=license-key=${HZ_LICENSE_KEY}
+          make test-e2e NAMESPACE=$NAMESPACE
 
-      # - name: Clean up after Tests
-      #   if: always()
-      #   run: |
-      #     DEPLOY_NAME=hazelcast-platform-controller-manager
-      #     hz=$(oc get hazelcast -o name); [[ "$hz" != "" ]] && oc delete $hz --wait=false || echo "no hazelcast resources"
-      #     mc=$(oc get managementcenter -o name); [[ "$mc" != "" ]] && oc delete $mc --wait=false || echo "no managementcenter resources"
-      #     if [[ ${{ steps.e2e-test.outcome }} != 'success' ]]; then
-      #       i=0
-      #       while ! oc rollout status deployment $DEPLOY_NAME; do
-      #         oc rollout restart deployment $DEPLOY_NAME
-      #         if [[ $i == 2 ]]; then echo "Failure testing the operator, namespace $NAMESPACE requires manual clean up"; exit 1; fi
-      #         ((i++))
-      #       done
-      #     fi
-      #     sleep 10
+      - name: Clean up after Tests
+        if: always()
+        run: |
+          DEPLOY_NAME=hazelcast-platform-controller-manager
+          hz=$(oc get hazelcast -o name); [[ "$hz" != "" ]] && oc delete $hz --wait=false || echo "no hazelcast resources"
+          mc=$(oc get managementcenter -o name); [[ "$mc" != "" ]] && oc delete $mc --wait=false || echo "no managementcenter resources"
+          if [[ ${{ steps.e2e-test.outcome }} != 'success' ]]; then
+            i=0
+            while ! oc rollout status deployment $DEPLOY_NAME; do
+              oc rollout restart deployment $DEPLOY_NAME
+              if [[ $i == 2 ]]; then echo "Failure testing the operator, namespace $NAMESPACE requires manual clean up"; exit 1; fi
+              ((i++))
+            done
+          fi
+          sleep 10
 
-      #     hz=$(oc get hazelcast -o name)
-      #     mc=$(oc get managementcenter -o name)
-      #     if [[ $hz != "" ]] || [[ $mc != "" ]]; then
-      #       echo "Failure deleting hazelcast and managementcenter resources, namespace $NAMESPACE requires manual clean up"; exit 1
-      #     fi
+          hz=$(oc get hazelcast -o name)
+          mc=$(oc get managementcenter -o name)
+          if [[ $hz != "" ]] || [[ $mc != "" ]]; then
+            echo "Failure deleting hazelcast and managementcenter resources, namespace $NAMESPACE requires manual clean up"; exit 1
+          fi
 
-      #     make undeploy 
-      #     oc delete secret hazelcast-license-key --wait=false
-      #     oc delete secret pull-secret --wait=false
-      #     oc delete project $NAMESPACE --wait=false  
+          make undeploy 
+          oc delete secret hazelcast-license-key --wait=false
+          oc delete secret pull-secret --wait=false
+          oc delete project $NAMESPACE --wait=false  
 
-      # - name: Publish the Hazelcast-Platform-Operator image
-      #   run: |
-      #     PROJECT_ID=$( echo ${RHEL_REPOSITORY} | grep -m 1 -Po "/\K.+(?=/)" )
-      #     source .github/scripts/publish-rhel.sh
+      - name: Publish the Hazelcast-Platform-Operator image
+        run: |
+          PROJECT_ID=$( echo ${RHEL_REPOSITORY} | grep -m 1 -Po "/\K.+(?=/)" )
+          source .github/scripts/publish-rhel.sh
 
-      #     publish_the_image "$PROJECT_ID" "$RELEASE_VERSION" "$RHEL_API_KEY"
+          publish_the_image "$PROJECT_ID" "$RELEASE_VERSION" "$RHEL_API_KEY"
 
-      #     wait_for_container_publish "$PROJECT_ID" "$RELEASE_VERSION" "$RHEL_API_KEY" "$TIMEOUT_IN_MINS"
+          wait_for_container_publish "$PROJECT_ID" "$RELEASE_VERSION" "$RHEL_API_KEY" "$TIMEOUT_IN_MINS"
 
   redhat_bundle_release:
     name: Create a PR in 
