Refactor tag release workflows for Dockerhub and RedHat
Other changes:
- Add 3 PR creation steps for the following repositories
   * community-operators -> for OperatorHub.io
   * community-operators-prod -> for OKD OpenSHift Container Platform
   * redhat-marketplace-operators -> for Red Hat Marketplace

diff --git a/.github/workflows/redhat-connect-release.yaml b/.github/workflows/redhat-connect-release.yaml
--- a/.github/workflows/redhat-connect-release.yaml
+++ b/.github/workflows/redhat-connect-release.yaml
@@ -3,6 +3,8 @@ on:
   push:
     tags:
       - "v*"
+env:
+  OPERATOR_NAME: "hazelcast-platform-operator"
 
 jobs:
   publish_image:
@@ -10,9 +12,10 @@ jobs:
     defaults:
       run:
         shell: bash
+    outputs:
+      RELEASE_VERSION: ${{ steps.set-outputs.outputs.RELEASE_VERSION }}
     env:
       SCAN_REGISTRY: "scan.connect.redhat.com"
-      OPERATOR_NAME: "hazelcast-platform-operator"
       TIMEOUT_IN_MINS: "60"
       RHEL_API_KEY: ${{ secrets.RHEL_API_KEY }}
       RHEL_REPOSITORY: ${{ secrets.RHEL_REPOSITORY }}
@@ -29,123 +32,149 @@ jobs:
       - name: Checkout to hazelcast-operator
         uses: actions/checkout@v2
 
-      - name: Generate Operator and Operator Image
+      - name: Set environment variables and job outputs
+        id: set-outputs
         run: |
           RHEL_IMAGE=${RHEL_REPOSITORY}:${RELEASE_VERSION}
           echo "RHEL_IMAGE=${RHEL_IMAGE}" >> $GITHUB_ENV
+          echo "::set-output name=RELEASE_VERSION::${RELEASE_VERSION}"
+      
+      # - name: Generate Operator and Operator Image
+      #   run: |
+      #     echo "Building the operator image"
+      #     make docker-build IMG=${RHEL_IMAGE} VERSION="${RELEASE_VERSION}"
 
-          echo "Building the operator image"
-          make docker-build IMG=${RHEL_IMAGE}
+      # - name: Push Hazelcast-Platform-Operator image to RHEL scan registry
+      #   run: |
+      #     docker login ${SCAN_REGISTRY} -u unused -p ${RHEL_REPO_PASSWORD}
+      #     make docker-push IMG=${RHEL_IMAGE} 
 
-      - name: Push Hazelcast-Platform-Operator image to RHEL scan registry
-        run: |
-          docker login ${SCAN_REGISTRY} -u unused -p ${RHEL_REPO_PASSWORD}
-          make docker-push IMG=${RHEL_IMAGE}
+      # - name: Wait for Scan to Complete
+      #   run: |
+      #     PROJECT_ID=$( echo ${RHEL_REPOSITORY} | grep -m 1 -Po "/\K.+(?=/)" )
+      #     source .github/scripts/publish-rhel.sh
 
-      - name: Wait for Scan to Complete
-        run: |
-          PROJECT_ID=$( echo ${RHEL_REPOSITORY} | grep -m 1 -Po "/\K.+(?=/)" )
-          source .github/scripts/publish-rhel.sh
+      #     wait_for_container_scan "$PROJECT_ID" "$RELEASE_VERSION" "$RHEL_API_KEY" "$TIMEOUT_IN_MINS"
 
-          wait_for_container_scan "$PROJECT_ID" "$RELEASE_VERSION" "$RHEL_API_KEY" "$TIMEOUT_IN_MINS"
+      # - name: Deploy Hazelcast-Platform-Operator to OCP
+      #   run: |
+      #     NAMESPACE=oc-e2e-test-${{ github.run_id}}
+      #     echo "NAMESPACE=${NAMESPACE}" >> $GITHUB_ENV
+      #     oc login ${OCP_CLUSTER_URL} -u=${OCP_USERNAME} -p=${OCP_PASSWORD} --insecure-skip-tls-verify
+      #     oc new-project $NAMESPACE
 
-      - name: Deploy Hazelcast-Platform-Operator to OCP
-        run: |
-          NAMESPACE=oc-e2e-test-${{ github.run_id}}
-          echo "NAMESPACE=${NAMESPACE}" >> $GITHUB_ENV
-          oc login ${OCP_CLUSTER_URL} -u=${OCP_USERNAME} -p=${OCP_PASSWORD} --insecure-skip-tls-verify
-          oc new-project $NAMESPACE
+      #     oc create secret docker-registry pull-secret \
+      #     --docker-server=$SCAN_REGISTRY \
+      #     --docker-username=unused \
+      #     --docker-password=$RHEL_REPO_PASSWORD \
+      #     --docker-email=unused
 
-          oc create secret docker-registry pull-secret \
-          --docker-server=$SCAN_REGISTRY \
-          --docker-username=unused \
-          --docker-password=$RHEL_REPO_PASSWORD \
-          --docker-email=unused
+      #     cat <<EOF | oc apply -f -
+      #     apiVersion: v1
+      #     kind: ServiceAccount
+      #     metadata:
+      #       name: hazelcast-platform-controller-manager
+      #       namespace: $NAMESPACE
+      #     EOF
 
-          cat <<EOF | oc apply -f -
-          apiVersion: v1
-          kind: ServiceAccount
-          metadata:
-            name: hazelcast-platform-controller-manager
-            namespace: $NAMESPACE
-          EOF
+      #     oc secrets link hazelcast-platform-controller-manager pull-secret --for=pull
+      #     make deploy  IMG=$RHEL_IMAGE  NAMESPACE=$NAMESPACE
+      #     oc rollout status deployment hazelcast-platform-controller-manager
 
-          oc secrets link hazelcast-platform-controller-manager pull-secret --for=pull
-          make deploy  IMG=$RHEL_IMAGE  NAMESPACE=$NAMESPACE
-          oc rollout status deployment hazelcast-platform-controller-manager
+      # - name: Test the Operator
+      #   id: e2e-test
+      #   run: |
+      #     oc create secret generic hazelcast-license-key --from-literal=license-key=${HZ_LICENSE_KEY}
+      #     make test-e2e NAMESPACE=$NAMESPACE
 
-      - name: Test the Operator
-        id: e2e-test
-        run: |
-          oc create secret generic hazelcast-license-key --from-literal=license-key=${HZ_LICENSE_KEY}
-          make test-e2e NAMESPACE=$NAMESPACE
+      # - name: Clean up after Tests
+      #   if: always()
+      #   run: |
+      #     DEPLOY_NAME=hazelcast-platform-controller-manager
+      #     hz=$(oc get hazelcast -o name); [[ "$hz" != "" ]] && oc delete $hz --wait=false || echo "no hazelcast resources"
+      #     mc=$(oc get managementcenter -o name); [[ "$mc" != "" ]] && oc delete $mc --wait=false || echo "no managementcenter resources"
+      #     if [[ ${{ steps.e2e-test.outcome }} != 'success' ]]; then
+      #       i=0
+      #       while ! oc rollout status deployment $DEPLOY_NAME; do
+      #         oc rollout restart deployment $DEPLOY_NAME
+      #         if [[ $i == 2 ]]; then echo "Failure testing the operator, namespace $NAMESPACE requires manual clean up"; exit 1; fi
+      #         ((i++))
+      #       done
+      #     fi
+      #     sleep 10
 
-      - name: Clean up after Tests
-        if: always()
-        run: |
-          DEPLOY_NAME=hazelcast-platform-controller-manager
-          hz=$(oc get hazelcast -o name); [[ "$hz" != "" ]] && oc delete $hz --wait=false || echo "no hazelcast resources"
-          mc=$(oc get managementcenter -o name); [[ "$mc" != "" ]] && oc delete $mc --wait=false || echo "no managementcenter resources"
-          if [[ ${{ steps.e2e-test.outcome }} != 'success' ]]; then
-            i=0
-            while ! oc rollout status deployment $DEPLOY_NAME; do
-              oc rollout restart deployment $DEPLOY_NAME
-              if [[ $i == 2 ]]; then echo "Failure testing the operator, namespace $NAMESPACE requires manual clean up"; exit 1; fi
-              ((i++))
-            done
-          fi
-          sleep 10
+      #     hz=$(oc get hazelcast -o name)
+      #     mc=$(oc get managementcenter -o name)
+      #     if [[ $hz != "" ]] || [[ $mc != "" ]]; then
+      #       echo "Failure deleting hazelcast and managementcenter resources, namespace $NAMESPACE requires manual clean up"; exit 1
+      #     fi
 
-          hz=$(oc get hazelcast -o name)
-          mc=$(oc get managementcenter -o name)
-          if [[ $hz != "" ]] || [[ $mc != "" ]]; then
-            echo "Failure deleting hazelcast and managementcenter resources, namespace $NAMESPACE requires manual clean up"; exit 1
-          fi
+      #     make undeploy 
+      #     oc delete secret hazelcast-license-key --wait=false
+      #     oc delete secret pull-secret --wait=false
+      #     oc delete project $NAMESPACE --wait=false  
 
-          make undeploy 
-          oc delete secret hazelcast-license-key --wait=false
-          oc delete secret pull-secret --wait=false
-          oc delete project $NAMESPACE --wait=false  
+      # - name: Publish the Hazelcast-Platform-Operator image
+      #   run: |
+      #     PROJECT_ID=$( echo ${RHEL_REPOSITORY} | grep -m 1 -Po "/\K.+(?=/)" )
+      #     source .github/scripts/publish-rhel.sh
+
+      #     publish_the_image "$PROJECT_ID" "$RELEASE_VERSION" "$RHEL_API_KEY"
+
+      #     wait_for_container_publish "$PROJECT_ID" "$RELEASE_VERSION" "$RHEL_API_KEY" "$TIMEOUT_IN_MINS"
+
+  redhat_bundle_release:
+    name: Create a PR in 
+    runs-on: ubuntu-latest
+    needs: publish_image
+    strategy:
+      fail-fast: false
+      matrix:
+        include:
+          - repo-name: redhat-marketplace-operators
+            repo-owner: redhat-openshift-ecosystem  
+            
+          - repo-name: certified-operators
+            repo-owner: redhat-openshift-ecosystem
+
+          - repo-name: community-operators-prod
+            repo-owner: redhat-openshift-ecosystem
+    env:
+      REPO_NAME: ${{ matrix.repo-name }}
+      REPO_OWNER: ${{ matrix.repo-owner }}
+      RELEASE_VERSION: ${{ needs.publish_image.outputs.RELEASE_VERSION }}
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2
 
       - name: Build Bundle
         run: |
-          make bundle IMG=${RHEL_IMAGE} VERSION=${RELEASE_VERSION}
+          RED_HAT_OPERATOR_REPOSITORY=registry.connect.redhat.com/hazelcast/${OPERATOR_NAME}
+          RED_HAT_OPERATOR_IMG=${RED_HAT_OPERATOR_REPOSITORY}:${RELEASE_VERSION}
 
+          make bundle IMG=${RED_HAT_OPERATOR_IMG} VERSION=${RELEASE_VERSION}
           cat >> ./bundle/metadata/annotations.yaml <<EOF
             # OpenShift annotations.
             com.redhat.openshift.versions: "v4.6"
           EOF
 
-      - name: Publish the Hazelcast-Platform-Operator image
+      - name: Validate Bundle for OCP
         run: |
-          PROJECT_ID=$( echo ${RHEL_REPOSITORY} | grep -m 1 -Po "/\K.+(?=/)" )
-          source .github/scripts/publish-rhel.sh
+          make bundle-ocp-validate
 
-          publish_the_image "$PROJECT_ID" "$RELEASE_VERSION" "$RHEL_API_KEY"
-
-          wait_for_container_publish "$PROJECT_ID" "$RELEASE_VERSION" "$RHEL_API_KEY" "$TIMEOUT_IN_MINS"
-
-      - name: Checkout to devOpsHelm/certified-operators
+      - name: Checkout to devOpsHelm/${{ env.REPO_NAME }}
         uses: actions/checkout@v2
         with:
-          repository: devOpsHelm/certified-operators
-          path: certified-operators
+          repository: devOpsHelm/${{ env.REPO_NAME }}
+          path: ${{ env.REPO_NAME }}
           token: ${{ secrets.DEVOPS_GITHUB_TOKEN }}
 
       - name: Update main branch of the fork
-        working-directory: certified-operators
+        working-directory: ${{ env.REPO_NAME }}
         run: |
-          export REPO_OWNER=redhat-openshift-ecosystem
-          export REPO_NAME=certified-operators
-          echo "REPO_OWNER=${REPO_OWNER}" >> $GITHUB_ENV
-          echo "REPO_NAME=${REPO_NAME}" >> $GITHUB_ENV
-
           git checkout main
-
           git remote add upstream https://github.com/${REPO_OWNER}/${REPO_NAME}.git
-
           git pull upstream main 
-
           git push origin main
 
       - name: Set Bundle Release Version
@@ -153,38 +182,39 @@ jobs:
           BUNDLE_RELEASE_VERSION=$( make print-bundle-version VERSION=${RELEASE_VERSION} )
           echo "BUNDLE_RELEASE_VERSION=${BUNDLE_RELEASE_VERSION}" >> $GITHUB_ENV
 
-      - name: Create a PR for Operatorhub-bundle, k8s-operatorhub
-        working-directory: certified-operators
+      - name: Commit and push changes to bundle
+        working-directory: ${{ env.REPO_NAME }}
         run: |
           git config user.email "devopshelm@hazelcast.com"
           git config user.name "devOpsHelm"
 
+          # Copy bundle files under new version of the operator
           git checkout -b ${OPERATOR_NAME}-${RELEASE_VERSION}-${{ github.run_id }}
-
           mkdir -p operators/${OPERATOR_NAME}/${BUNDLE_RELEASE_VERSION}
           cp -r ../bundle/manifests ../bundle/metadata operators/${OPERATOR_NAME}/${BUNDLE_RELEASE_VERSION}/
 
+          # Commit and push changes
           git add  ./operators/${OPERATOR_NAME}
-
           git commit --signoff -m "Update ${OPERATOR_NAME} to ${RELEASE_VERSION}"
+          git push -u origin ${OPERATOR_NAME}-${BUNDLE_RELEASE_VERSION}-${{ github.run_id }}
 
-          git push -u origin ${OPERATOR_NAME}-${RELEASE_VERSION}-${{ github.run_id }}
-
+      - name: Create PR 
+        working-directory: ${{ env.REPO_NAME }}
+        run: |
           echo ${{ secrets.DEVOPS_GITHUB_TOKEN }} | gh auth login --with-token
-
           gh pr create --title "operator ${OPERATOR_NAME} (${BUNDLE_RELEASE_VERSION})" --body "" --repo ${REPO_OWNER}/${REPO_NAME}
 
   slack_notify:
     name: Slack Notify
-    needs: publish_image
+    needs: ['publish_image', 'redhat_bundle_release']
     runs-on: ubuntu-latest
     if: always()
     steps:
       - uses: 8398a7/action-slack@f3635935f58910a6d6951b73efe9037c960c8c04
-        if: needs.publish_image.result != 'success'
+        if: needs.publish_image.result != 'success' || needs.redhat_bundle_release.result != 'success'
         with:
           fields: repo,commit,author,action,eventName,workflow
-          status: ${{ needs.publish_image.result }}
+          status: ${{ needs.redhat_bundle_release.result }}
           channel: "#github-actions-log"
         env:
           SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
